<?php
/**
 * Jean Jean Inc.
 * 
 *
 * @category   Laurent
 * @package    ${Package}
 * @author     Laurent Clouet <laurent35240@gmail.com>
 * @date       3/17/13
 * @copyright  Copyright (c) 2012 Jean Jean Inc. (http://laurent-clouet.fr/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0) 
 */
/**
 * @var $this Laurent_Twittercards_Block_Meta
 */
?>
<meta name="twitter:card" content="summary" />
<meta name="twitter:url" content="<?php echo $this->getCanonicalUrl(); ?>" />
<meta name="twitter:title" content="<?php echo $this->getTitle(); ?>"/>
<meta name="twitter:description" content="<?php echo $this->getDescription(); ?>" />